# Generated by Django 6.0.4 on 2026-05-01 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='settings/')),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=200)),
                ('description', models.TextField(max_length=300)),
                ('fb_link', models.URLField()),
                ('inst_link', models.URLField()),
                ('address', models.CharField(default='Belém, Pará', max_length=200)),
            ],
        ),
    ]
