# Generated by Django 6.0.4 on 2026-05-16 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_banner_propaganda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrossel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título da Imagem')),
                ('image', models.ImageField(upload_to='carrossel/', verbose_name='Imagem do Carrossel')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link (opcional)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem (1, 2, 3...)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Carrossel',
                'verbose_name_plural': 'Carrossel',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
